export const listE1 = [
  "1 time a year/ once a year",
  "2 times a years",
  "abide by",
  "accompany",
  "accountable for",
  "acquire",
  "address",
  "adopt",
  "advertisement",
  "anniversary",
  "appoint",
  "approve",
  "arrange",
  "assess",
  "assignment",
  "attach",
  "attempt",
  "attract",
  "banquet/ reception",
  "be subject to",
  "before",
  "board",
  "book",
  "browse",
  "careful",
  "carpooling",
  "carry out",
  "certainly",
  "change",
  "chief",
  "competition",
  "compulsory",
  "coworker",
  "current",
  "decent",
  "demand",
  "discount",
  "document",
  "drink",

  // "ecological",
  //   "emphasize",
  //   "establish",
  //   "estimate",
  //   "eventual/ultimate",
  //   "every other year",
  //   "excel at/in",
  //   "exhibit",
  //   "existing",
  //   "expand",
  //   "expenditure",
  //   "famous",
  //   "favor",
  //   "feedback/ questionaire",
  //   "figure",
  //   "figure out",
  //   "finalize",
  //   "fire",
  //   "free / complimentary",
  //   "frequently",
  //   "give",
  //   "go over",
  //   "hire",
  //   "hold",
  //   "in view of/ as a result of",
  //   "Inc / company",
  //   "initial",
  //   "inquire",
  //   "interest",
  //   "inventory",
  //   "job opening",
  //   "job opening",
  //   "journal",
  //   "largely",
  //   "latest",
  //   "launch",
  //   "let up",
  //   "lobby",
  //   "luggage",
  //   "mall",
  //   "marked",
  //   "meet (demand/requirement)",
  //   "meeting",
  //   "merchandise",
  //   "monitor",
  //   "necessary",
  //   "negotiate",
  //   "obtain/ gain",
  //   "occasionally",
  //   "offer",
  //   "offerings",
  //   "offline = onsite",
  //   "opportunity",
  //   "parking pass",
  //   "part",
  //   "participate in",
  //   "patron",
  //   "persuade",
  //   "previous",
  //   "problem",
  //   "produce",
  //   "productivity",
  //   "prohibit",
  //   "promotion",
  //   "promptly",
  //   "propose",
  //   "provided that/as long as",
  //   "publication",
  //   "publisher",
  //   "punctual",
  //   "purchase",
  //   "qualified for",
  //   "quarter(ly)",
  //   "rarely",
  //   "reach/achieve/accomplish",
  //   "reasonable",
  //   "receipt",
  //   "recover",
  //   "reduce",
  //   "reference /referal",
  //   "refund",
  //   "regarding",
  //   "register",
  //   "regularly",
  //   "reject",
  //   "reliable",
  //   "renovate",
  //   "respond to/reply to",
  //   "reveal",
  //   "sample",
  //   "secret",
  //   "seeing that/now that/since/as",
  //   "significant",
  //   "socket",
  //   "solve",
  //   "state of the art",
  //   "submit",
  //   "supervise",
  //   "surgery",
  //   "talk to",
  //   "target",
  //   "trade show",
  //   "trip",
  //   "valid",
  //   "vendor",
  //   "venture",
  //   "waiter",
  //   "wear",
  //   "wholesome",
  //   "work",
  //   "work from home",
];

export const listE2 = [
  "yearly/annualy",
  "every six months/ biannual",
  "comply with/ follow",
  "go with",
  "responsible for/in charge of",
  "obtain",
  "speak to",
  "aprove",
  "commercial",
  "ceremony/ celebration",
  "assign",
  "agree with",
  "organize",
  "evaluate/review",
  "task",
  "include, enclose, send with",
  "effort",
  "appeal to",
  "dinner",
  "prior to/ ahead of",

  "panel",
  "reserve/ order",
  "access",
  "cautious",
  "share car",
  "implement/administer/",
  "sure/definitely/absolutely",
  "modify",
  "boss/leader",
  "contest",
  "mandatory",
  "colleague",
  "now",
  "fine/good",
  "needs",
  "voucher/coupon/ speacial",
  "offer/ promotion",
  "material",
  "beverage",
  "environmental",
];
